language: rust
sudo: true
os: 
  - linux

matrix:
  fast_finish: false
  include:
include:
  - rust: stable
    install:
    before_script:
      - rustup component add clippy
    script:
      - cargo check
      - cargo build --release --verbose --all
      - cargo test --release --verbose --all
      - cargo clippy -- -D warnings

  - rust: beta
    install:
    script:
      - cargo check
      - cargo build --release --verbose --all
      - cargo test --release --verbose --all

  - rust: nightly
    install:
    script:
      - cargo check
      - cargo build --release --verbose --all
      - cargo test --release --verbose --all


# Send a notification to the Dusk build Status Telegram channel once the CI build completes
after_script:
  - bash <(curl -s https://raw.githubusercontent.com/dusk-network/tools/master/bash/telegram_ci_notifications.sh)

after_success:
  # Upload docs
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        echo "<meta http-equiv=refresh content=0;url=plonk_gadgets/index.html>" > target/doc/index.html &&
        git clone https://github.com/davisp/ghp-import.git &&
        ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
        echo "Uploaded documentation"
      fi