[package]
name = "plonk_gadgets"
version = "0.1.0"
authors = ["CPerezz <c.perezbaro@gmail.com>",
"Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plonk = {git = "https://github.com/dusk-network/plonk"}
jubjub = {git = "https://github.com/zkcrypto/jubjub"}
