[package]
name = "plonk_gadgets"
version = "0.1.0"
authors = ["CPerezz <c.perezbaro@gmail.com>", "Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"


[dependencies]
dusk-plonk = {version = "0.2.7", features = ["trace", "trace-print"]}
anyhow = "1.0.32"
thiserror = "1.0.20"

[dev-dependencies]
rand = "0.7.3"
rand_core = "0.5.1"