[package]
name = "plonk_gadgets"
version = "0.1.0"
authors = ["CPerezz <c.perezbaro@gmail.com>", "Victor Lopez <vhrlopes@gmail.com>"]
edition = "2018"


[dependencies]
dusk-plonk = "0.2.6"
anyhow = "1.0.32"
thiserror = "1.0.20"

[dev-dependencies]
rand = "0.7.3"
