[package]
name = "plonk_gadgets"
version = "0.4.1"
authors = ["CPerezz <carlos@dusk.network>", "Kevaundray Wedderburn <kev@dusk.network>", "Victor Lopez <victor@dusk.network>"]
edition = "2018"


[dependencies]
dusk-plonk = {version = "0.3.3", features = ["trace-print"]}
anyhow = "1"
thiserror = "1"

[dev-dependencies]
rand = "0.7.3"
rand_core = "0.5.1"