[package]
name = "plonk_gadgets"
version = "0.2.1"
authors = ["CPerezz <carlos@dusk.network>", "Kevaundray Wedderburn <kev@dusk.network>", "Victor Lopez <victor@dusk.network>"]
edition = "2018"


[dependencies]
dusk-plonk = {git = "https://github.com/dusk-network/plonk", branch ="circuit_trait_ref", features = ["trace-print"]}
anyhow = "1.0.32"
thiserror = "1.0.20"

[dev-dependencies]
rand = "0.7.3"
rand_core = "0.5.1"